import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
import {readFileSync,readdirSync} from 'node:fs';
const sql=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
class Statement{constructor(q,values=[]){this.q=q;this.values=values}bind(...values){return new Statement(this.q,values)}async first(){return sql.prepare(this.q).get(...this.values)??null}async all(){return {results:sql.prepare(this.q).all(...this.values),success:true,meta:{}}}async run(){sql.prepare(this.q).run(...this.values);return {success:true,results:[],meta:{}}}}
const jar=new Map();const context={env:{DB:{prepare:q=>new Statement(q)}},headers:new Headers(),jar,redirect:p=>{throw Error('REDIRECT:'+p)}};
globalThis.__roamlyTest=context;
const compiled=await build({entryPoints:['tests/auth-history-entry.ts'],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'test-runtime',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},args=>({path:args.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({loader:'js',contents:args.path==='cloudflare:workers'?'export const env=globalThis.__roamlyTest.env':args.path==='next/navigation'?'export const redirect=globalThis.__roamlyTest.redirect':`export async function headers(){return globalThis.__roamlyTest.headers} export async function cookies(){const jar=globalThis.__roamlyTest.jar;return {get:n=>jar.has(n)?{name:n,value:jar.get(n).value}:undefined,getAll:()=>Array.from(jar,([name,c])=>({name,value:c.value})),set:(name,value,options)=>jar.set(name,{value,options}),delete:name=>jar.delete(name)}}`}));}}]});
const app=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const input={destination:'Auckland',startDate:'',days:5,travelers:2,budget:'Comfort',pace:'Balanced',interests:['Nature'],needs:'',homeCity:''};
const origin='https://roamly.test';
function user(id='alice'){context.headers=new Headers({'oai-authenticated-user-id':id,'oai-authenticated-user-email':id+'@example.test'});}
function req(path,data,method='POST'){return new Request(origin+path,{method,headers:{origin,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})})}
test('anonymous users cannot read history or submit searches',async()=>{context.headers=new Headers();assert.equal((await app.history.GET(req('/api/history',undefined,'GET'))).status,401);assert.equal((await app.generate.POST(req('/api/generate',input))).status,401);assert.equal(sql.prepare('SELECT count(*) AS n FROM search_history').get().n,0)});
let aucklandId;
test('Auckland followed by Austria retains both searches when AI is unavailable',async()=>{user();for(const destination of ['Auckland','Austria'])assert.equal((await app.generate.POST(req('/api/generate',{...input,destination}))).status,503);const r=await app.history.GET(req('/api/history',undefined,'GET'));assert.equal(r.status,200);const {entries}=await r.json();assert.equal(entries.length,2);assert.deepEqual(new Set(entries.map(x=>x.intake.destination)),new Set(['Auckland','Austria']));assert.ok(entries.every(x=>x.status==='failed'));aucklandId=entries.find(x=>x.intake.destination==='Auckland').id;const restored=await (await app.history.GET(req('/api/history?id='+aucklandId,undefined,'GET'))).json();assert.equal(restored.entry.intake.destination,'Auckland');assert.equal(restored.entry.intake.days,5)});
test('another user cannot list, fetch or delete the first account’s searches',async()=>{user('bob');assert.deepEqual((await (await app.history.GET(req('/api/history',undefined,'GET'))).json()).entries,[]);assert.equal((await app.history.GET(req('/api/history?id='+aucklandId,undefined,'GET'))).status,404);await app.history.DELETE(req('/api/history',{id:aucklandId},'DELETE'));user();assert.equal((await app.history.GET(req('/api/history?id='+aucklandId,undefined,'GET'))).status,200)});
test('completed results are persisted and can be reopened without another AI call',async()=>{user();const id=await app.repository.startSearch(context.env.DB,'alice',input);await app.repository.completeSearch(context.env.DB,'alice',id,app.sample.sampleTrip);const entry=await app.repository.findSearch(context.env.DB,'alice',id);assert.equal(entry.status,'completed');assert.deepEqual(entry.trip,app.sample.sampleTrip)});
test('pagination retains older searches and never crosses account boundaries',async()=>{for(let i=0;i<22;i++)await app.repository.startSearch(context.env.DB,'pagination-user',{...input,destination:'Search '+i});const first=await app.repository.historyPage(context.env.DB,'pagination-user');const second=await app.repository.historyPage(context.env.DB,'pagination-user',20);assert.equal(first.entries.length,20);assert.equal(first.hasMore,true);assert.equal(second.entries.length,2);assert.equal(second.hasMore,false);assert.equal(new Set([...first.entries,...second.entries].map(x=>x.id)).size,22)});
test('CSRF and malformed requests are rejected before history insertion',async()=>{user();const n=sql.prepare('SELECT count(*) AS n FROM search_history').get().n;const bad=new Request(origin+'/api/generate',{method:'POST',headers:{origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify(input)});assert.equal((await app.generate.POST(bad)).status,403);assert.equal((await app.generate.POST(req('/api/generate',{...input,days:100}))).status,400);assert.equal(sql.prepare('SELECT count(*) AS n FROM search_history').get().n,n)});
test('unconfigured Google/email methods fail closed and cannot create sessions',async()=>{assert.equal((await app.google.POST(req('/api/auth/google',{}))).status,503);assert.equal((await app.email.POST(req('/api/auth/email',{email:'a@example.test'}))).status,503);assert.equal((await app.verify.POST(req('/api/auth/verify',{email:'a@example.test',token:'123456'}))).status,503);assert.equal(jar.size,0)});
test('sign-out immediately prevents platform fallback and protects history',async()=>{user();assert.ok(await app.identity.currentUser());assert.equal((await app.logout.POST(req('/api/auth/logout',{}))).status,200);assert.equal(await app.identity.currentUser(),null);assert.equal((await app.history.GET(req('/api/history',undefined,'GET'))).status,401);assert.equal(jar.get('roamly-signed-out').options.httpOnly,true);jar.clear()});
test('redirect destinations cannot escape the site or loop into authentication',()=>{for(const p of ['https://evil.test','//evil.test','/\\evil.test','/auth/callback','/api/auth/google','/signout-with-chatgpt','/\n/evil'])assert.equal(app.policy.safeReturnTo(p),'/');assert.equal(app.policy.safeReturnTo('/?history=abc'),'/?history=abc')});
test('callback without a valid OAuth code never authenticates',async()=>{const r=await app.callback.GET(req('/auth/callback',undefined,'GET'));assert.equal(r.status,303);assert.equal(new URL(r.headers.get('Location')).pathname,'/auth');assert.equal(jar.size,0)});
const mockUser={id:'ccff879e-8be1-4b9b-95eb-3604734052a3',aud:'authenticated',role:'authenticated',email:'verified@example.test',email_confirmed_at:new Date().toISOString(),app_metadata:{provider:'email'},user_metadata:{full_name:'Test Explorer'},identities:[],created_at:new Date().toISOString()};
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
const fakeAccess=[encode({alg:'HS256',typ:'JWT'}),encode({sub:mockUser.id,exp:Math.floor(Date.now()/1000)+3600,iat:Math.floor(Date.now()/1000),aud:'authenticated',role:'authenticated'}),'fixture-signature'].join('.');
const fakeSession={access_token:fakeAccess,refresh_token:'fixture-refresh-not-a-real-secret',expires_in:3600,token_type:'bearer',user:mockUser};
const realFetch=globalThis.fetch;let calls=[];
function enableMockProvider(){context.env.SUPABASE_URL='https://fixture.supabase.co';context.env.SUPABASE_PUBLISHABLE_KEY='fixture-public-key';context.env.SUPABASE_AUTH_ENABLED='true';globalThis.fetch=async(input,init)=>{const u=new URL(typeof input==='string'?input:input.url);assert.equal(u.origin,'https://fixture.supabase.co');calls.push(u.pathname);const data=init?.body?JSON.parse(init.body):{};if(u.pathname.endsWith('/otp'))return Response.json({});if(u.pathname.endsWith('/verify'))return data.token==='123456'?Response.json(fakeSession):Response.json({msg:'Token has expired or is invalid',code:'otp_expired'},{status:403});if(u.pathname.endsWith('/user'))return Response.json(mockUser);if(u.pathname.endsWith('/token')){assert.ok(data.code_verifier);return Response.json(fakeSession)}if(u.pathname.endsWith('/logout'))return new Response(null,{status:204});throw Error('Unexpected provider endpoint');};}
test('email OTP uses the real SDK and establishes a server-verified HttpOnly session with a mocked provider',async()=>{jar.clear();enableMockProvider();const sent=await app.email.POST(req('/api/auth/email',{email:mockUser.email}));assert.equal(sent.status,200);const bad=await app.verify.POST(req('/api/auth/verify',{email:mockUser.email,token:'000000'}));assert.equal(bad.status,400);assert.ok(!jar.get('roamly-auth-provider'));const good=await app.verify.POST(req('/api/auth/verify',{email:mockUser.email,token:'123456',returnTo:'/history'}));assert.equal(good.status,200);assert.equal((await good.json()).redirectTo,'/history');assert.equal((await app.identity.currentUser()).id,'supabase:'+mockUser.id);assert.ok(Array.from(jar).filter(([k])=>k.startsWith('sb-')).every(([,v])=>v.options.httpOnly===true));assert.ok(calls.includes('/auth/v1/verify'));assert.ok(calls.includes('/auth/v1/user'));});
test('Google start stores PKCE and callback exchanges its code with the mocked provider',async()=>{jar.clear();const start=await app.google.POST(req('/api/auth/google',{returnTo:'/history'}));assert.equal(start.status,200);const {url}=await start.json();const u=new URL(url);assert.equal(u.origin,'https://fixture.supabase.co');assert.equal(u.searchParams.get('provider'),'google');assert.equal(u.searchParams.get('code_challenge_method'),'s256');assert.ok(u.searchParams.get('code_challenge'));assert.ok(Array.from(jar.keys()).some(k=>k.includes('code-verifier')));const callback=await app.callback.GET(req('/auth/callback?code=fixture-code',undefined,'GET'));assert.equal(callback.status,303);assert.equal(callback.headers.get('Location'),origin+'/history');assert.equal((await app.identity.currentUser()).id,'supabase:'+mockUser.id);});
test('expired external identity cannot silently fall back to another platform account',async()=>{jar.clear();jar.set('roamly-auth-provider',{value:'supabase',options:{}});user();assert.equal(await app.identity.currentUser(),null);});
test('external sign-out revokes session through provider and clears cookies',async()=>{jar.clear();await app.verify.POST(req('/api/auth/verify',{email:mockUser.email,token:'123456'}));assert.equal((await app.logout.POST(req('/api/auth/logout',{}))).status,200);assert.equal(await app.identity.currentUser(),null);assert.ok(!Array.from(jar.keys()).some(k=>k.startsWith('sb-')));assert.ok(calls.includes('/auth/v1/logout'));globalThis.fetch=realFetch;context.env.SUPABASE_AUTH_ENABLED='false';jar.clear();});
