"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, MapPin, Plus, UsersRound, LockKeyhole, Share2 } from "lucide-react";
import { type Outing, type OutingInput, type JoinRequest } from "@/lib/trips/together";
import { TripFooter } from "./footer";
import { TripEditor, type EditorMode } from "./together-editor";
const blank=(hostName=""):OutingInput=>({id:crypto.randomUUID(),title:"",hostName,city:"",destination:"",startDate:"",capacity:3,summary:"",cost:0,days:[""],meeting:""});
async function api(path:string, data?:unknown){
  const r=await fetch('/api/together'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});
  const json=await r.json(); if(!r.ok) throw Error(json.error??'Unable to load trips. Try again.'); return json;
}
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
export function Together({signedIn,plus,membershipUnavailable=false,hostName=""}:{signedIn:boolean;plus:boolean;membershipUnavailable?:boolean;hostName?:string}){
  const [tab,setTab]=useState<'discover'|'mine'|'create'>('discover');
  const [trips,setTrips]=useState<Outing[]>([]),[trip,setTrip]=useState<Outing|null>(null),[requests,setRequests]=useState<JoinRequest[]>([]);
  const [draft,setDraft]=useState<OutingInput|null>(null),[draftMode,setDraftMode]=useState<EditorMode>('new'),[city,setCity]=useState(''),[destination,setDestination]=useState(''),[date,setDate]=useState('');
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [name,setName]=useState(''),[intro,setIntro]=useState(''),[meeting,setMeeting]=useState(''),[report,setReport]=useState(''),[reportOpen,setReportOpen]=useState(false);
  const version=useRef(0),locked=useRef(false);
  async function load(id?:string,mine=tab==='mine'){
    const request=++version.current;setLoading(true);setError('');
    try {
      const result=await api(id?'?id='+encodeURIComponent(id):'?'+new URLSearchParams(mine?{mine:'1'}:{city,destination,date}));
      if(request!==version.current)return;
      if(id){setTrip(result.trip);setRequests(result.requests);setMeeting(result.trip.meeting??'');setReportOpen(false);setReport('');}
      else {setTrip(null);setTrips(result.trips);}
    }catch(e){if(request===version.current)setError((e as Error).message);}
    finally{if(request===version.current)setLoading(false);}
  }
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('trip');void load(id??undefined,false);return()=>{version.current++;};},[]); // Initial shared link; filters apply on submit.
  function open(id:string){window.history.replaceState(null,'','/together?trip='+encodeURIComponent(id));setDraft(null);setNotice('');void load(id);}
  function switchTab(next:typeof tab){version.current++;setTab(next);setTrip(null);setError('');setNotice('');window.history.replaceState(null,'','/together');if(next==='create'){setLoading(false);if(!draft){setDraft(blank(hostName));setDraftMode('new');}}else void load(undefined,next==='mine');}
  async function act(action:string,extra:Record<string,unknown>={},id=trip?.id){
    if(locked.current||!id)return; locked.current=true;setBusy(true);setError('');setNotice('');
    try {await api('',{action,id,...extra});if(action==='save')setDraft(null);setNotice(action==='report'?'Report saved. It does not automatically remove this trip.':action==='join'?'Request sent. Check My activity for the host’s decision.':action==='save'?(extra.publish?'Your trip is live. Share it to find company.':draftMode==='published'?'Changes saved. Everyone who requested or joined has been notified.':'Draft saved. Publish it whenever you’re ready.'):action==='publish'?'Your trip is live. Share it to find company.':'Changes saved.');await load(id);}
    catch(e){setError((e as Error).message);}finally{locked.current=false;setBusy(false);}
  }
  const input=(key:keyof OutingInput,value:unknown)=>setDraft(d=>d?{...d,[key]:value}:d);
  const edit=(t:Outing,mode:EditorMode)=>{setDraft({id:t.id,title:t.title,hostName:t.hostName,city:t.city,destination:t.destination,startDate:t.startDate,capacity:t.capacity,summary:t.summary,cost:t.cost,days:t.days,meeting:t.meeting??''});setDraftMode(mode);setTrip(null);setTab('create');setNotice('');window.history.replaceState(null,'','/together');};
  const auth=<Link className="primary" href={'/auth?returnTo='+encodeURIComponent(trip?'/together?trip='+trip.id:'/together')}>Sign in to continue <ArrowRight size={16}/></Link>;
  return <main className="workspace together">
    <div className="page-heading"><div><span className="eyebrow">GOOD PLANS. BETTER COMPANY.</span><h1>Travel together.</h1><p className="subtext">Start in your city. Share your itinerary. Find your kind of travel people.</p></div><span className="together-plus">Hosting with Roamly Plus</span></div>
    <div className="together-tabs" aria-label="Travel together views">{(['discover','mine','create'] as const).map(t=><button type="button" key={t} disabled={busy} aria-pressed={tab===t&&!trip} className={tab===t&&!trip?'active':''} onClick={()=>switchTab(t)}>{t==='discover'?'Discover trips':t==='mine'?'My activity':<><Plus size={16}/> Create a trip</>}</button>)}</div>
    {error&&<div className="together-message" role="alert">{error} <button type="button" onClick={()=>void load(trip?.id)}>Refresh</button></div>}
    {notice&&<p className="together-message success" role="status">{notice}</p>}
    {loading?<p role="status" className="panel">Loading trips…</p>:trip?<>
      <button className="text-button" disabled={busy} onClick={()=>switchTab(tab==='create'?'mine':tab)}><ArrowLeft size={16}/> Back to trips</button>
      <div className="together-detail">
        <section className="panel"><div className="together-card-top"><span className="eyebrow">{trip.status} · HOSTED BY {trip.hostName}</span>{!['draft','discarded'].includes(trip.status)&&<button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin+'/together?trip='+trip.id);setNotice('Trip link copied.');}catch{setNotice('Copy the trip link from your address bar.');}}}><Share2 size={16}/> Share</button>}</div>
          <h2>{trip.title}</h2><p className="subtext">{trip.city} → {trip.destination} · {dateLabel(trip.startDate)}</p>{trip.summary&&<p className="together-prose">{trip.summary}</p>}
          <h3>The itinerary</h3>{trip.days.length?trip.days.map((day,i)=><section className="together-day" key={i}><span className="eyebrow">DAY {i+1}</span><p className="together-prose">{day}</p></section>):<p className="subtext">The host hasn’t added a day-by-day plan yet. Ask about it when you request to join.</p>}
          <p className="form-note">Plans are shared by travellers. Hosts are not verified tour operators. Agree on arrangements directly; Roamly does not collect trip payments.</p>
          {signedIn&&!trip.isHost&&trip.status!=='draft'&&<><button className="text-button" onClick={()=>setReportOpen(!reportOpen)}>Report a concern</button>{reportOpen&&<form onSubmit={e=>{e.preventDefault();void act('report',{reason:report});}}><label>What concerns you?<textarea required minLength={10} maxLength={1000} value={report} onChange={e=>setReport(e.target.value)}/></label><button className="secondary-button" disabled={busy}>Submit report</button><p className="form-note">Reports are stored for site-owner review. No automatic removal or emergency response.</p></form>}</>}
        </section>
        <aside className="together-aside"><section className="panel"><h3><UsersRound size={20}/> Room for good company</h3><p><strong>{Math.max(0,trip.capacity-trip.approved)}</strong> of {trip.capacity} guest places available</p><p>{trip.days.length?`${trip.days.length} ${trip.days.length===1?'day':'days'} · `:''}{trip.cost?`₹${trip.cost.toLocaleString('en-IN')} estimated per person`:'Cost to be shared by the host'}</p><p className="form-note">Host’s estimate, not a booking price. Requesting is free; approval is required.</p>
          {['cancelled','discarded'].includes(trip.status)?<p role="status">This trip was cancelled. Please do not travel on this plan.</p>:trip.isHost?<><p>You’re the host.</p>{['draft','open','closed'].includes(trip.status)&&<button className="secondary-button" disabled={!plus||busy} onClick={()=>edit(trip,trip.status==='draft'?'draft':'published')}>{trip.status==='draft'?'Edit draft':'Edit trip'}</button>}{['draft','closed'].includes(trip.status)&&<button className="primary" disabled={!plus||busy} onClick={()=>void act('publish')}>{trip.status==='draft'?'Publish itinerary':'Reopen requests'}</button>}{trip.status==='open'&&<button className="secondary-button" disabled={busy} onClick={()=>void act('close')}>Close new requests</button>}<button className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Cancel this trip? It will be marked cancelled for everyone. This cannot be undone.'))void act('cancel');}}>Cancel trip</button>{!plus&&<p className="form-note">You can manage existing travellers. Editing and publishing need an active Plus membership.</p>}</>:trip.requestStatus?<><p className="together-status">Your request: <strong>{trip.requestStatus}</strong></p>{['pending','approved'].includes(trip.requestStatus)&&<button className="secondary-button" disabled={busy} onClick={()=>{if(window.confirm('Withdraw from this trip? You cannot request this same trip again.'))void act('withdraw');}}>Withdraw from trip</button>}</>:!signedIn?auth:trip.status!=='open'||trip.capacity<=trip.approved?<p>Requests are closed or all places are filled.</p>:<form onSubmit={e=>{e.preventDefault();void act('join',{name,message:intro});}}><label>Your name for the host<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>A little about you<textarea required minLength={10} maxLength={500} placeholder="Your interests and why you’d like to join…" value={intro} onChange={e=>setIntro(e.target.value)}/></label><p className="form-note">Only the host can see your introduction. Each request is for one person.</p><button className="primary" disabled={busy}>{busy?'Sending…':'Request to join'}</button></form>}
        </section>
        {(trip.isHost||trip.requestStatus==='approved')&&trip.status!=='cancelled'&&<section className="panel"><h3><LockKeyhole size={18}/> Private coordination</h3>{trip.isHost?<form onSubmit={e=>{e.preventDefault();void act('meeting',{meeting});}}><label>Meeting and contact details<textarea maxLength={2000} value={meeting} onChange={e=>setMeeting(e.target.value)}/></label><p className="form-note">Shared only with approved travellers. Add only contact details you consent to share.</p><button className="secondary-button" disabled={busy}>Save private details</button></form>:<p className="together-prose">{trip.meeting||'The host has not added meeting details yet. Check back before departure.'}</p>}</section>}
        {trip.isHost&&<section className="panel"><h3>Travellers & requests</h3>{!requests.length?<p className="subtext">No requests yet. Publish and share your trip to find company.</p>:requests.map(r=><div className="together-request" key={r.member}><strong>{r.name}</strong><span className="eyebrow">{r.status}</span><p className="together-prose">{r.message}</p>{r.status==='pending'&&<div className="together-actions"><button className="primary" disabled={busy||trip.status!=='open'||trip.approved>=trip.capacity} onClick={()=>void act('approve',{member:r.member})}>Approve</button><button className="secondary-button" disabled={busy} onClick={()=>void act('decline',{member:r.member})}>Decline</button></div>}{r.status==='approved'&&<button className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Remove this traveller and revoke their access to private details?'))void act('remove',{member:r.member});}}>Remove traveller</button>}</div>)}</section>}
        <button className="text-button" disabled={busy} onClick={()=>void load(trip.id)}>Refresh latest status</button></aside>
      </div>
    </>:tab==='create'?<>{!signedIn?<section className="panel"><h2>Your next adventure starts with a plan.</h2><p>Sign in to host with Roamly Plus.</p>{auth}</section>:!plus?<section className="panel"><span className="eyebrow">ROAMLY PLUS · ₹499 FOR 30 DAYS</span><h2>Bring your people together.</h2><p>{membershipUnavailable?'Membership could not be checked. Refresh to try again.':'Hosting requires an active Plus membership. Browsing and requesting to join are free.'}</p><Link className="primary" href="/pricing">Explore Roamly Plus <ArrowRight size={16}/></Link></section>:draft&&<TripEditor draft={draft} mode={draftMode} busy={busy} onChange={(k,v)=>input(k,v)} onSave={publish=>void act('save',{trip:draft,publish},draft.id)} onCancel={()=>{const id=draft.id;setDraft(null);open(id);}}/>}</>:<>
        {tab==='discover'?<form className="panel together-filters" onSubmit={e=>{e.preventDefault();void load();}}><label>Leaving from<input maxLength={100} value={city} onChange={e=>setCity(e.target.value)} placeholder="Try Bareilly"/></label><label>Going to<input maxLength={100} value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Anywhere"/></label><label>Departure date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary">Find company <ArrowRight size={16}/></button></form>:<p className="subtext">Your hosted trips and requests, with the latest status. Open a trip to manage it.</p>}
        {tab==='mine'&&!signedIn?<section className="panel">{auth}</section>:trips.length?<div className="together-grid">{trips.map(t=><article className="panel together-card" key={t.id}><div className="together-card-top"><span className="eyebrow">{t.isHost?'YOUR TRIP':t.requestStatus??'OPEN INVITATION'}</span><span>{t.status}</span></div><h2>{t.title}</h2><p className="subtext">with {t.hostName}</p><p><MapPin size={16}/>{t.city} → {t.destination}</p><p><CalendarDays size={16}/>{dateLabel(t.startDate)}{t.days.length?` · ${t.days.length} ${t.days.length===1?'day':'days'}`:''}</p><p><UsersRound size={16}/>{Math.max(0,t.capacity-t.approved)} guest places left</p>{t.summary&&<p className="together-excerpt">{t.summary}</p>}<div className="together-card-bottom"><span>{t.cost?`~₹${t.cost.toLocaleString('en-IN')} / person`:'Cost to be shared'}</span><button className="text-button" onClick={()=>open(t.id)}>View trip <ArrowRight size={16}/></button></div></article>)}</div>:<section className="panel together-empty"><UsersRound size={36}/><h2>{tab==='mine'?'Your next chapter is waiting.':'No trips here yet.'}</h2><p className="subtext">{tab==='mine'?'Find a trip to join or create your own with Plus.':'Try a nearby city or different dates, or be the first to host.'}</p><button className="primary" onClick={()=>switchTab(tab==='mine'?'discover':'create')}>{tab==='mine'?'Discover trips':'Create a trip'}</button></section>}
        <p className="form-note">Discover shows up to 50 upcoming trips. My activity shows your latest 100 trips and requests. Check the notification bell for new trip updates. No email notifications are sent.</p>
      </>}
    <TripFooter/>
  </main>;
}
